### ISSUE TITLE
Enchantment Description still showing.

### ISSUE THREAD

**Issue by Drebledore** [iron431/rpg-tweaks#4]
Hello! In the enchantment module, when you have [enchantment description ](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions) it would still show the description making identifying them null. If I may suggest, make it so it hides the entire tooltip of the item itself. This also makes it more mysterious especially if you are playing with apotheosis which adds prefixes/ random attributes to items.

**Comment by iron431** [comment]
I have both mods installed and everything is working on my end. Can you attach a screenshot of the issue as well as all other mods you're using?

**Comment by Drebledore** [comment]
After some testing, I found out it was [CoFH Core](https://www.curseforge.com/minecraft/mc-mods/cofh-core). I tested the loot on dungeons and it seems to be random. Some give out descriptions but mostly it works as intended. 

The mods on the screenshot are RPG tweaks, CoFH core, and when dungeons arise.
![enchant-desc](https://github.com/iron431/rpg-tweaks/assets/66674044/39cb7325-cada-4a6a-b5ce-d7980cf570a0)

**Comment by iron431** [comment]
For some reason, CoFH core places descriptions on enchanted books if they only have 1 enchantment.
It also looks like they have a client config to turn it off

**Comment by BugmanBugman** [comment]
![2023-08-02_13 23 56](https://github.com/iron431/rpg-tweaks/assets/40730042/5e9e3cdb-a9c7-4f05-8da3-a558650c6c64)
![2023-08-02_13 23 54](https://github.com/iron431/rpg-tweaks/assets/40730042/0825c382-faaf-4545-ace9-ffc5151727dc)
Seems to be happening in 1.20.1, but no COFH. Just with enchantment descriptions and https://www.curseforge.com/minecraft/mc-mods/held-item-tooltips

**Comment by paladin-alys** [comment]
Confirmed happening in 1.20.1 with no COFH.
![image](https://github.com/iron431/rpg-tweaks/assets/87140134/2bea20db-e931-411b-978c-26cc983eba74)

**Comment by AetheriMC** [comment]
I put in a compat request with Enchantment Descriptions who pointed out that the description visibility is resulting from a bug. They pointed out in the code where they think the bug is derived.

https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/216

https://github.com/iron431/rpg-tweaks/blob/b58c9dd49d689e0e2f1a1cc87185ee6838be580a/src/main/java/io/redspace/ironsrpgtweaks/enchantment_module/EnchantmentClientEvents.java#L52

**Comment by iron431** [comment]
Currently, it works on 1.19.2 with Enchantment Descriptions 13.0.14. Their code is identical on 1.19.2 and 1.20.1, so I would have to look into this deeper as to why it wouldn't be working 
<img width="281" alt="image" src="https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/34083081/d98add47-834b-44f0-a024-2d449a042c54">
<img width="625" alt="image" src="https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/assets/34083081/af7853b2-2e8a-486b-aa9c-f443861a901c">
Their code on 1.19.2:
https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/blob/1.19.2/Common/src/main/java/net/darkhax/enchdesc/DescriptionManager.java
Their code on 1.20.1:
https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/blob/1.20.1/common/src/main/java/net/darkhax/enchdesc/DescriptionManager.java

**Comment by iron431** [comment]
Correction; it does work on 1.20.1. Perceived issues may be related to mod loading order. I'll release a patch that _should_ make sure our code gets executed last, but otherwise, this issue is resolved.
<img width="360" alt="image" src="https://github.com/iron431/rpg-tweaks/assets/34083081/f348e085-7acd-4b52-a862-f0cba8286646">
<img width="607" alt="image" src="https://github.com/iron431/rpg-tweaks/assets/34083081/17dc9ab1-902c-43a4-9e70-640fc6199205">
